#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch Polybar, using default config location ~/.config/polybar/config
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    if [ "$m" = "eDP-1" ]; then
      MON_DPI=192 MONITOR=$m polybar --reload laptopbar &
    elif [ "$m" = "DP-2" ]; then
      MON_DPI=110 MONITOR=$m polybar --reload laptopbar &
    else
      MON_DPI=96 MONITOR=$m polybar --reload laptopbar &
    fi
  done
else
  polybar --reload laptopbar &
fi

echo "Polybar launched..."

